# Generated by Django 5.2.4 on 2025-07-29 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(help_text='Chọn nếu là Nam', verbose_name='Giới tính (Nam)')),
                ('age', models.FloatField(verbose_name='Tuổi')),
                ('debt', models.FloatField(verbose_name='Nợ')),
                ('married', models.BooleanField(verbose_name='Đã kết hôn')),
                ('bank_customer', models.BooleanField(verbose_name='Là khách hàng ngân hàng')),
                ('industry', models.CharField(choices=[('CommunicationServices', 'Dịch vụ Viễn thông'), ('ConsumerDiscretionary', 'Tiêu dùng không thiết yếu'), ('ConsumerStaples', 'Tiêu dùng thiết yếu'), ('Education', 'Giáo dục'), ('Energy', 'Năng lượng'), ('Financials', 'Tài chính'), ('Healthcare', 'Y tế'), ('Industrials', 'Công nghiệp'), ('InformationTechnology', 'Công nghệ thông tin'), ('Materials', 'Vật liệu'), ('RealEstate', 'Bất động sản'), ('Research', 'Nghiên cứu'), ('Transport', 'Giao thông Vận tải'), ('Utilities', 'Tiện ích')], max_length=50, verbose_name='Ngành công nghiệp')),
                ('ethnicity', models.CharField(choices=[('Asian', 'Châu Á'), ('Black', 'Da đen'), ('Latino', 'Latin'), ('White', 'Da trắng'), ('Other', 'Khác')], max_length=20, verbose_name='Sắc tộc')),
                ('years_employed', models.FloatField(verbose_name='Số năm làm việc')),
                ('prior_default', models.BooleanField(verbose_name='Có nợ xấu trong quá khứ')),
                ('employed', models.BooleanField(verbose_name='Có việc làm')),
                ('credit_score', models.IntegerField(verbose_name='Điểm tín dụng')),
                ('drivers_license', models.BooleanField(verbose_name='Có giấy phép lái xe')),
                ('citizen', models.CharField(choices=[('ByBirth', 'Theo nơi sinh'), ('ByOtherMeans', 'Theo cách khác'), ('Temporary', 'Tạm thời')], max_length=20, verbose_name='Tình trạng công dân')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Mã bưu điện')),
                ('income', models.IntegerField(verbose_name='Thu nhập')),
                ('approval_result', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kết quả phê duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đơn đăng ký tín dụng',
                'verbose_name_plural': 'Các đơn đăng ký tín dụng',
                'ordering': ['-created_at'],
            },
        ),
    ]
